services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: linux_monitor
      POSTGRES_USER: andrej
      POSTGRES_PASSWORD: StrongPassword123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    pid: "host"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/linux_monitor
      SPRING_DATASOURCE_USERNAME: andrej
      SPRING_DATASOURCE_PASSWORD: StrongPassword123!
      STATS_SCRIPT_PATH: /app/stats.py
    depends_on:
      - db

volumes:
  postgres_data:
