spring.application.name=linux-monitor

spring.datasource.url=jdbc:postgresql://localhost:5432/linux_monitor
spring.datasource.username=andrej
spring.datasource.password=StrongPassword123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

stats.script.path=${STATS_SCRIPT_PATH:/home/at95/Desktop/linux-monitor/stats.py}